# Generated by Django 4.2.4 on 2023-08-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=100, unique=True), max_length=100, unique=True),
        ),
    ]
